hasker/hasker/hasker/hasker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = (
    [
        path("", RedirectView.as_view(url="posts")),
        path("posts/", include("posts.urls")),
        path("admin/", admin.site.urls),
    ]
    + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
)

hasker/hasker/hasker/posts/urls.py
from django.conf import settings
from django.contrib.auth.views import LogoutView
from django.urls import path

from . import views

app_name = "posts"
urlpatterns = [
    # ex: /posts/
    path("", views.IndexViewLast.as_view(), name="index"),
    # ex: /posts/hot/
    path("hot/", views.IndexViewHot.as_view(), name="index_hot"),
    # ex: /posts/search/
    path("search/", views.SearchResultsList.as_view(), name="search_results"),
    # ex: /posts/search_by_tag/
    path("tag/<str:tag>", views.IndexViewByTag.as_view(), name="search_by_tag"),
    # ex: /posts/5/
    path("<int:pk>/", views.question_view, name="detail"),
    # ex: /posts/register
    path("register/", views.register, name="register"),
    # ex: /posts/login
    path("login/", views.login_view, name="login"),
    # ex: /posts/logout
    path("logout/", LogoutView.as_view(), {"next_page": settings.LOGOUT_REDIRECT_URL}, name="logout"),
    # ex: /posts/add_question
    path("add_question/", views.add_question, name="add_question"),
    # ex: /posts/5/add_answer
    path("<int:pk>/add_answer/", views.add_answer, name="add_answer"),
    # ex: posts/change_answer_rate/
    path("change_answer_rate/", views.change_answer_rate, name="change_answer_rate"),
    # ex: /posts/change_question_rate/
    path("change_question_rate/", views.change_question_rate, name="change_question_rate"),
    # ex: /posts/cancel_answer_vote/
    path("cancel_answer_vote/", views.cancel_answer_vote, name="cancel_answer_vote"),
    # ex: /posts/cancel_question_vote/
    path("cancel_question_vote/", views.cancel_question_vote, name="cancel_question_vote"),
    # ex: /posts/5/choose_the_best/1
    path("<int:pk_question>/choose_the_best/<int:pk_answer>", views.choose_the_best, name="choose_the_best"),
]

hasker/hasker/hasker/posts/models.py
from django.conf import settings
from django.db import models

User = settings.AUTH_USER_MODEL


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Question(models.Model):
    title = models.TextField()
    text = models.TextField()
    pub_date = models.DateTimeField("published date", auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="questions")
    votes = models.IntegerField(default=0)
    tags = models.ManyToManyField(Tag, related_name="tag")
    found_answer = models.BooleanField(default=False)

    def __str__(self):
        return self.title


class QuestionVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="qh_user")
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="qh_question")
    is_plus = models.BooleanField(default=True)


class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="answers")
    text = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="authors")
    pub_date = models.DateTimeField("published date", auto_now_add=True)
    votes = models.IntegerField(default=0)
    is_right = models.BooleanField(default=False)

    @staticmethod
    def get_answers(question):
        answers = question.answers.all()
        for answer in answers:
            answer.already_vote = AnswerVote.objects.filter(answer=answer).exists()
        return answers

    def __str__(self):
        return self.text


class AnswerVote(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="aq_user")
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, related_name="aq_answer")
    is_plus = models.BooleanField(default=True)

hasker/hasker/hasker/posts/forms.py
from django import forms
from django.apps import apps
from django.contrib.auth.forms import UserCreationForm

from .models import Answer, Question

CustomUser = apps.get_model("users", "CustomUser")


class AddQuestionForm(forms.ModelForm):
    title = forms.CharField(max_length=255, label="Title", widget=forms.TextInput)
    text = forms.CharField(widget=forms.Textarea(attrs={"cols": 60, "rows": 10}), label="Question")
    tags = forms.CharField(max_length=255, label="Tag", widget=forms.TextInput)

    class Meta:
        model = Question
        fields = ["title", "text", "tags"]


class AddAnswerForm(forms.ModelForm):
    text = forms.CharField(widget=forms.Textarea(attrs={"cols": 60, "rows": 10}), label="Answer")

    class Meta:
        model = Answer
        fields = ["text"]


class RegisterUserForm(UserCreationForm):
    username = forms.CharField(max_length=255, label="Nickname")
    password1 = forms.PasswordInput()
    password2 = forms.PasswordInput()
    email = forms.EmailField()
    avatar = forms.ImageField()

    class Meta:
        model = CustomUser
        # Для отображения всех полей: fields = "__all__"
        fields = ["username", "password1", "password2", "email", "avatar"]

hasker/hasker/hasker/posts/views.py
import logging
import re
from smtplib import SMTPException

from django.conf import settings
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import AuthenticationForm
from django.core.mail import send_mail
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render
from django.utils import timezone
from django.views import generic

from .forms import AddAnswerForm, AddQuestionForm, RegisterUserForm
from .models import Answer, AnswerVote, Question, QuestionVote, Tag

MAX_ANSWERS_PER_PAGE = 30
MAX_QUESTIONS_PER_PAGE = 20


# Create your views here.
class IndexViewLast(generic.ListView):
    template_name = "posts/index.html"
    context_object_name = "latest_question_list"
    paginate_by = MAX_QUESTIONS_PER_PAGE

    def get_queryset(self):
        """
        Получить набор из вопросов, сортированных по дате публикации

        lte = меньше или равно
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")


class IndexViewHot(generic.ListView):
    template_name = "posts/index.html"
    context_object_name = "latest_question_list"
    paginate_by = MAX_QUESTIONS_PER_PAGE

    def get_queryset(self):
        """
        Получить набор из вопросов, сортированных по дате публикации

        lte = меньше или равно
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-votes")


class IndexViewByTag(generic.ListView):
    template_name = "posts/index.html"
    context_object_name = "latest_question_list"
    paginate_by = MAX_QUESTIONS_PER_PAGE

    def get_queryset(self):
        """
        Получить набор из вопросов, сортированных по тегу
        """
        tag = self.request.GET.get("tag")
        return Question.objects.filter(tags__name__exact=tag).order_by("-votes", "-pub_date")


class SearchResultsList(generic.ListView):
    model = Question
    context_object_name = "latest_question_list"
    template_name = "posts/search_results.html"
    paginate_by = MAX_QUESTIONS_PER_PAGE

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["query"] = self.request.GET.get("q")
        return context

    def get_queryset(self):
        query = self.request.GET.get("q")
        # Поиск по тегу: tag:<имя тега>
        found = re.match(r"^tag:(\w+)", query)
        if found:
            tag = found.group(1)
            return Question.objects.filter(tags__name__exact=tag).order_by("-votes", "-pub_date")
        # Поиск по вопросу
        return Question.objects.filter(
            Q(title__icontains=query) | Q(text__icontains=query) | Q(title__iexact=query) | Q(text__iexact=query)
        ).order_by("-votes", "-pub_date")


def question_view(request, pk):
    question = get_object_or_404(Question, pk=pk)
    question.already_vote = QuestionVote.objects.filter(question=question).exists()
    answers = Answer.get_answers(question)
    answers = _get_page_obj(request, answers, MAX_ANSWERS_PER_PAGE)
    return render(request, "posts/detail.html", {"question": question, "page_obj": answers})


def register(request):
    """Регистрация нового пользователя"""
    if request.method == "POST":
        form = RegisterUserForm(request.POST, request.FILES)
        if form.is_valid():
            try:
                new_user = form.save(commit=False)
                new_user.email = form.cleaned_data["email"]
                new_user.avatar = form.cleaned_data["avatar"]
                new_user.save()
                return redirect("posts:login")
            except Exception:
                form.add_error(None, "Failed to add user")
    else:
        form = RegisterUserForm()
    return render(request, "posts/register.html", {"form": form})


def login_view(request):
    """Аутентификация пользователя"""
    if request.method == "POST":
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get("username")
            password = form.cleaned_data.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("posts:index")
            else:
                messages.error(request, "Invalid username or password.")
        else:
            messages.error(request, "Invalid username or password.")
    form = AuthenticationForm()
    return render(request=request, template_name="posts/login.html", context={"login_form": form})


def add_question(request):
    """Добавление нового вопроса"""
    if request.method == "POST":
        form = AddQuestionForm(request.POST)
        if form.is_valid():
            try:
                question = form.save(commit=False)
                question.author = request.user
                question.save()
                tags = parse_tags(request.POST.get("tags"))
                if len(tags) > 3:
                    messages.info(request, "Only three tags can be set.")
                for tag in tags[:3]:
                    tag = Tag(name=tag)
                    tag.save()
                    question.tags.add(tag)
                return redirect("posts:detail", pk=question.id)
            except Exception:
                form.add_error(None, "Failed to add question")
    else:
        form = AddQuestionForm()
    return render(request, "posts/add_question.html", {"form": form})


def parse_tags(tags: str) -> list:
    """Преобразование тегов из строки в список"""
    tags_list = tags.split(",")
    print(tags_list)
    return tags_list


def add_answer(request, pk):
    """Добавление нового ответа на вопрос"""
    if request.method == "POST":
        form = AddAnswerForm(request.POST)
        if form.is_valid():
            try:
                answer = form.save(commit=False)
                answer.author = request.user
                answer.question_id = pk
                answer.save()
                # Отправляем email автору вопроса
                try:
                    question = get_object_or_404(Question, pk=pk)
                    email = question.author.email
                    send_mail(
                        "Hasker: new answer",
                        f"User {request.user.username} sent answer " f"to your question {question.title}.",
                        settings.EMAIL_HOST_USER,
                        [email],
                    )
                except SMTPException:
                    logging.error(f"Error sending email to {email}")

                return redirect("posts:detail", pk=pk)
            except Exception:
                form.add_error(None, "Failed to add response")
    else:
        form = AddAnswerForm()
    return render(request, "posts/add_answer.html", {"form": form, "pk": pk})


def change_answer_rate(request):
    """Изменение рейтинга ответа"""
    pk_question = request.POST.get("question_id")
    pk_answer = request.POST.get("answer_id")
    vote = int(request.POST.get("vote"))

    question = get_object_or_404(Question, pk=pk_question)
    question.already_vote = QuestionVote.objects.filter(question=question).exists()
    answer = get_object_or_404(Answer, pk=pk_answer)
    already_vote = AnswerVote.objects.filter(user=request.user).filter(answer=answer)
    if not already_vote:
        votes = answer.votes + vote
        is_plus = vote == 1
        Answer.objects.filter(pk=pk_answer).update(votes=votes)
        # Добавляем информацию о голосовании пользователя
        vote = AnswerVote(user=request.user, answer=answer, is_plus=is_plus)
        vote.save()
    else:
        messages.error(request, "To re-vote, cancel your vote.")
    answers = Answer.get_answers(question)
    answers = _get_page_obj(request, answers, MAX_ANSWERS_PER_PAGE)
    return render(request, "posts/detail.html", {"question": question, "page_obj": answers})


def change_question_rate(request):
    """Изменение рейтинга вопроса"""
    pk_question = request.POST.get("question_id")
    vote = int(request.POST.get("vote"))

    question = get_object_or_404(Question, pk=pk_question)
    question.already_vote = QuestionVote.objects.filter(question=question).exists()
    already_vote = QuestionVote.objects.filter(user=request.user).filter(question=question)
    if not already_vote:
        votes = question.votes + vote
        is_plus = vote == 1
        Question.objects.filter(pk=pk_question).update(votes=votes)
        # Добавляем информацию о голосовании пользователя
        vote = QuestionVote(user=request.user, question=question, is_plus=is_plus)
        vote.save()
    else:
        messages.error(request, "To re-vote, cancel your vote.")
    answers = Answer.get_answers(question)
    answers = _get_page_obj(request, answers, MAX_ANSWERS_PER_PAGE)
    return render(request, "posts/detail.html", {"question": question, "page_obj": answers})


def choose_the_best(request, pk_question, pk_answer):
    """Выбрать наилучший ответ"""
    Question.objects.filter(pk=pk_question).update(found_answer=True)
    Answer.objects.filter(pk=pk_answer).update(is_right=True)
    question = get_object_or_404(Question, pk=pk_question)
    question.already_vote = QuestionVote.objects.filter(question=question).exists()
    answers = Answer.get_answers(question)
    answers = _get_page_obj(request, answers, MAX_ANSWERS_PER_PAGE)
    return render(request, "posts/detail.html", {"question": question, "page_obj": answers})


def cancel_answer_vote(request):
    """Отменить голос ответа"""
    pk_question = request.POST.get("question_id")
    pk_answer = request.POST.get("answer_id")

    votes = AnswerVote.objects.filter(user=request.user).filter(answer_id=pk_answer)
    roll_vote = 1 if votes[0].is_plus else -1
    votes.delete()

hasker/hasker/hasker/posts/templates/posts/add_answer.html
{% extends 'posts/layout.html' %}

{% block title %}Добавление ответа{% endblock %}

{% block content %}
    <form action="{% url "posts:add_answer" pk %}" method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }} </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit">Add</button>

    </form>

{% endblock %}

hasker/hasker/hasker/posts/templates/posts/add_question.html
{% extends 'posts/layout.html' %}

{% block title %}Adding a Question{% endblock %}

{% block content %}

    <form action="{% url "posts:add_question" %}" method="post">
    {% csrf_token %}

    <div class="form-error">{{ form.non_field_errors }}</div>

    {% for f in form %}
        <p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}: </label>{{ f }} </p>
        <div class="form-error">{{ f.errors }}</div>
    {% endfor %}

    <button type="submit">Add</button>

    </form>

{% endblock %}

hasker/hasker/hasker/posts/templates/posts/detail.html
{% extends 'posts/layout.html' %}

{% block title %}Question: {{ question.title }}{% endblock %}


{% block content %}

{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}


<div class="container p-3 my-3 bg-primary text-white">
    <h3>{{ question.title }}</h3>
    <h5>{{ question.text }}</h5>
    <h5>{{ question.pub_date }}</h5>
    <h5>Author: {{ question.author }}</h5>
    <h5>Rate: {{ question.votes }}</h5>

    {% for tag in question.tags.all %}
        {{tag.name}}
    {% endfor %}
    <br>

{% if user.is_authenticated %}
    <a href="{% url 'posts:add_answer' question.id %}">
       <button type="button" class="btn-outline-light">Add answer
       </button>
    </a>

        <div class="btn-group">
            <form method="post" action="{% url 'posts:change_question_rate' %}">
            {% csrf_token %}
            <input type="hidden" name="question_id" value="{{question.id}}">
            <input type="hidden" name="vote" value="1">
            <button class="btn-outline-light" type="submit">+</button>
            </form>

            <form method="post" action="{% url 'posts:change_question_rate' %}">
            {% csrf_token %}
            <input type="hidden" name="question_id" value="{{question.id}}">
            <input type="hidden" name="vote" value="-1">
            <button class="btn-outline-light" type="submit">-</button>
            </form>
        </div>

    {% if question.already_vote %}
        <div class="btn-group">
            <form method="post" action="{% url 'posts:cancel_question_vote' %}">
            {% csrf_token %}
            <input type="hidden" name="question_id" value="{{question.id}}">
            <button class="btn-outline-light" type="submit">Cancel vote</button>
            </form>
        </div>
    {% else %}
    {% endif %}

{% else %}
{% endif %}
</div>

    <br>
    {% for answer in page_obj %}
    <div class="container p-3 my-3 border">
        <h5>{{ answer.text }}</h5>
        <h5>{{ answer.author }}</h5>
        <h5>{{ answer.pub_date }}</h5>
        <h5>{{ answer.votes }}</h5>

        {% if answer.is_right %}
            <div class="form-check">
              <input class="form-check-input" type="checkbox" value="" id="flexCheckChecked" checked disabled>
              <label class="form-check-label" for="flexCheckChecked">
                Лучший ответ!
              </label>
            </div>
        {% else %}
        {% endif %}

{% if user.is_authenticated %}
        <div class="btn-group">
            <form method="post" action="{% url 'posts:change_answer_rate' %}">
            {% csrf_token %}
            <input type="hidden" name="question_id" value="{{question.id}}">
            <input type="hidden" name="answer_id" value="{{answer.id}}">
            <input type="hidden" name="vote" value="1">
            <button class="btn btn-primary" type="submit">+</button>
            </form>

            <form method="post" action="{% url 'posts:change_answer_rate' %}">
            {% csrf_token %}
            <input type="hidden" name="question_id" value="{{question.id}}">
            <input type="hidden" name="answer_id" value="{{answer.id}}">
            <input type="hidden" name="vote" value="-1">
            <button class="btn btn-primary" type="submit">-</button>
            </form>
        </div>

        {% if user == question.author and not question.found_answer%}
                 <a href="{% url 'posts:choose_the_best' question.id answer.id %}">
                   <button type="button" class="btn-outline-light">Choose the best!
                   </button>
                </a>
        {% else %}
        {% endif %}

        {% if answer.already_vote %}
            <div class="btn-group">
                <form method="post" action="{% url 'posts:cancel_answer_vote' %}">
                {% csrf_token %}
                <input type="hidden" name="question_id" value="{{question.id}}">
                <input type="hidden" name="answer_id" value="{{answer.id}}">
                <button class="btn-outline-light" type="submit">Cancel vote</button>
                </form>
            </div>
        {% else %}
        {% endif %}

{% else %}
{% endif %}

    </div>
    {% endfor %}


<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

hasker/hasker/hasker/posts/templates/posts/index.html
{% extends 'posts/layout.html' %}

{% block title %}Hasker{% endblock %}

{% block content %}
    <h4><div class="btn-group">
    <a href="{% url 'posts:index' %}"><h4><b>New questions</b> &nbsp</h4></a>
    <a href="{% url 'posts:index_hot' %}"><h4><b>Hot questions</b></h4></a>
    </div></h4>

    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <div class="shadowbox">
                <li><a href="{% url 'posts:detail' question.id %}"><h5>{{ question.title }}</h5> <h6><b>Rate</b>: {{ question.votes }}</h6></a></li>
                <h7>{{ question.text }}</h7> <h6><b>Author:</b> {{ question.author }}</h6>

                Tags: <h6>{{ question.pub_date }}</h6>{% for tag in question.tags.all %}
                    <a href="{% url 'posts:search_by_tag' tag.name %}?tag={{ tag.name }}"><h5>{{ tag.name }}</h5></a>
                {% endfor %}

            </div>
            <h1></h1>
        {% endfor %}
        </ul>
    {% else %}
        <p>No question are available.</p>
    {% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}

hasker/hasker/hasker/posts/templates/posts/layout.html
{% load static %}
{% load posts_tags %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'posts/css/posts.css' %}">
</head>
<body>
     <div class="topnav">
         <img src="{% static 'posts/img/hasker_image.png' %}" alt="Logo">
      <a class="active" href="{% url 'posts:index' %}">Main</a>

      {% if user.is_authenticated %}
          <a href="{% url 'posts:add_question' %}">Ask</a>
          <a href="{% url 'posts:logout' %}">Log out</a>
          <h6>User: {{ user.username }}</h6>

         {% if user.avatar %}
         <div class="float-end"><img src="{{ user.avatar.url }}" class="img-fluid"></div><br>

         {% endif %}

      {% else %}
          <a href="{% url 'posts:register' %}">Register</a> | <a href="{% url 'posts:login' %}">Log in</a>
      {% endif %}

    <form action="{% url 'posts:search_results' %}" method="get">
      <input
        type="search"
        name="q"
        placeholder="Search by questions..."
        class="form-control"
      />
    </form>

    </div>

     <aside>
         <h3>Trending</h3>
         {% get_most_rate_questions as most_rate_questions %}
         {% for question in most_rate_questions %}
            <div class="shadowbox">
                <li><a href="{% url 'posts:detail' question.id %}"><h5>Rate: {{ question.votes }} {{ question.title }}
                </h5></a></li>
            </div>
         {% endfor %}

     </aside>

     <main>
         {% block content %}
         {% endblock %}
     </main>

</body>
</html>

hasker/hasker/hasker/posts/templates/posts/login.html
{% extends 'posts/layout.html' %}

{% block title %}Sign in{% endblock %}

{% block content %}
    <h2>Authentication</h2><br>

    <div class="container py-5">
      <h1>Login</h1>
      <form method="POST">
        {% csrf_token %}
        {{ login_form }}
        <button class="btn btn-primary" type="submit">Login</button>
      </form>
      <p class="text-center">Don't have an account? <a href="{% url 'posts:register' %}">Create an account</a>.</p>
    </div>
{% endblock %}

hasker/hasker/hasker/posts/templates/posts/register.html
{% extends 'posts/layout.html' %}

{% block title %}Registration on the website{% endblock %}

{% block content %}
    <h2>Регистрация</h2><br>

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>

    </form>
{% endblock %}

hasker/hasker/hasker/posts/templates/posts/search_results.html
{% extends 'posts/layout.html' %}

{% block title %}Результаты поиска{% endblock %}

{% block content %}
    <h2>Questions</h2><br>
    <div class="btn-group">
    <li><a href="{% url 'posts:index' %}"><h5>New questions</h5></a></li>
    <li><a href="{% url 'posts:index_hot' %}"><h5>Hot questions</h5></a></li>
    </div>

    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <div class="shadowbox">
                <li><a href="{% url 'posts:detail' question.id %}"><h5>{{ question.title }}</h5></a></li>
                <h7>{{ question.text }}</h7>
                <br><br>
                <h7>Author: {{ question.author }}, Rate: {{ question.votes }}, {{ question.pub_date }}</h7>

                <b>Tag:</b> {% for tag in question.tags.all %}
                    {{ tag.name }}
                {% endfor %}

            </div>
            <h1></h1>
        {% endfor %}
        </ul>
    {% else %}
        <p>No question are available.</p>
    {% endif %}

<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1&q={{ query }}">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}&q={{ query }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}&q={{ query }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}&q={{ query }}ы">last &raquo;</a>
        {% endif %}
    </span>
</div>

{% endblock %}